performance-feedback/Internet/Controllers/GoalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Internet.Controllers
{
    public class GoalController : Controller
    {
        //
        // GET: /Goal/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

    }
}

performance-feedback/Internet/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Internet.Controllers
{
    public class TaskController : Controller
    {
        //
        // GET: /Task/

        public ActionResult Index()
        {
            return View();
        }

    }
}

performance-feedback/Internet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/site.css")" rel="stylesheet" type="text/css" />    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="brand" href="@Url.Content("~/")">Twitter Bootstrap MVC</a>
                @Html.Partial("_NavPartial")
                @Html.Partial("_LogOnPartial")
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()        
        <hr />
        <footer>
            <p>
                &copy; Company 2012</p>
        </footer>
    </div>
    <script src="@Url.Content("~/Scripts/jquery-1.8.0.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/site.js")" type="text/javascript"></script>
</body>
</html>

performance-feedback/Internet/Views/Shared/_LayoutFluid.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />    
    <link href="@Url.Content("~/Content/site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap-responsive.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css3-microsoft-metro-buttons/css/msft-metro-buttons.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="row-fluid">
        <div class="span10 offset1">
            <div class="navbar">
              <div class="navbar-inner">
                <div class="container-fluid" style="padding-top:20px;">
                  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </a>
                  <a class="brand" href=""><img src="../../Content/images/headerlogo.png" /></a>          
                  @Html.Partial("_LogOnPartial")
                  <div class="nav-collapse">
                    @Html.Partial("_NavPartial")
                  </div><!--/.nav-collapse -->
                </div>
              </div>
            </div>

            <div class="row-fluid">
                <div class="span12">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
      

      <hr />

      <footer>
        <p>&copy; QuickPayroll 2012</p>
      </footer>

    </div><!--/.fluid-container-->
    <script src="@Url.Content("~/Scripts/jquery-1.8.0.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/site.js")" type="text/javascript"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="http://code.highcharts.com/modules/exporting.js"></script>
</body>
</html>

performance-feedback/Internet/Views/Shared/_LayoutOuter.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" type="text/css" />    
    <link href="@Url.Content("~/Content/site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap-responsive.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css3-microsoft-metro-buttons/css/msft-metro-buttons.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span10 offset1">
            <div class="navbar">
              <div class="navbar-inner">
                <div class="container-fluid">
                  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </a>
                  <a class="brand" href=""><img src="../../Content/images/loginlogo.png" /></a>
                  <div class="nav-collapse">
                    @Html.Partial("_LogOnPartial")
                  </div><!--/.nav-collapse -->
                </div>
              </div>
            </div>
            @RenderBody()
        </div>
      </div>

      <hr />

      <footer>
        <p>&copy; QuickPayroll 2012</p>
      </footer>

    </div><!--/.fluid-container-->
    <script src="@Url.Content("~/Scripts/jquery-1.8.0.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/site.js")" type="text/javascript"></script>
</body>
</html>

performance-feedback/Internet/Views/Shared/_LogOnPartial.cshtml
<ul class="nav pull-right">
    @if (Request.IsAuthenticated)
    {         
        <li class="dropdown">
            <div class="span2">
                <ul class="thumbnails">
                    <li class="span12">
                        <div class="thumbnail">
                          <a href="#"><img src="../../Content/images/Picture1.png" alt="avatar" /></a>                          
                        </div>
                    </li>
                </ul>
            </div>      
            <div class="span10" style="padding-top:10px;"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
                @User.Identity.Name <b class="caret"></b></a>  
                <ul class="dropdown-menu">
                    <li>
                        @Html.ActionLink("Profile", "ChangePassword", "Account")
                    </li>
                    <li>
                        @Html.ActionLink("Log Off", "LogOff", "Account")
                    </li>
                </ul> 
            </div>  
        </li>
    }
    else
    {
        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Guest
            <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li>
                    @Html.ActionLink("Log On", "LogOn", "Account")
                </li>
                <li>
                    @Html.ActionLink("Register", "Register", "Account")
                </li>
            </ul>
        </li>
    }
</ul>

performance-feedback/Internet/Views/Shared/_NavPartial.cshtml
<ul class="nav">   
    <li><a href="@Url.Content("~/Dashboard/index")" id="dashboard">Dashboard</a></li>  
    <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Goals
        <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>@Html.ActionLink("My Goals", "Index", "Goal")</li>
            <li>@Html.ActionLink("My Tasks", "Index", "Task")</li>
        </ul>
    </li>  
    <li>@Html.ActionLink("Performance", "Index", "Performance")</li> 
    <li>@Html.ActionLink("Appraisal", "Index", "Appraisal")</li> 
    <li>@Html.ActionLink("Network", "Index", "Network")</li>    
    <li><a href="@Url.Content("~/Dashboard/index")" id="about">Team</a></li>          
</ul>                                   

performance-feedback/Internet/Views/Shared/_SidebarPartial.cshtml
<div class="well sidebar-nav">
    <ul class="nav nav-list">
        <li class="nav-header">Sidebar</li>
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="nav-header">Sidebar</li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="nav-header">Sidebar</li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
    </ul>
</div>
<!--/.well -->